export const golpes = [
  "Jab",
  "Recto",
  "Desplazamiento lateral (hacia la derecha)",
  "Hook izquierdo",
  "Desplazamiento lateral (hacia la izquierda)",
  "Uppercut derecho",
  "Esquiva hacia la izquierda",
  "Esquiva hacia la derecha",
  "Bloqueo alto",
  "Pausa (un segundo)",
  "Jab al cuerpo",
  "Recto al cuerpo",
  "Uppercut izquierdo al cuerpo",
  "Hook derecho a la cabeza",
  "Esquiva hacia atrás",
  "Hook derecho",
  "Desplazamiento hacia adelante",
  "Bloqueo bajo",
  "Esquiva hacia adelante",
  "Desplazamiento hacia atrás",
  "Roll hacia la izquierda",
  "Roll hacia la derecha"
]
